### PR TITLE
Fix migrations name & Remove seller middleware

### PR DESCRIPTION
**Pull request by IdjiotSandwiches**
1. Rename migration to migration convention name
2. Remove seller related middleware & migrations
3. Remove seller route

### CODE REVIEW

**Comment by IdjiotSandwiches** [comment]
Updates:
1. Fix error page navbar authentication by using fallback route
2. Admin cannot access user/unauthenticated pages

**Comment by IdjiotSandwiches** [comment]
Updates:
1. Fix auth navbar for admin
2. Throw 404 page when accessing not authorized page

**Comment by appleaze** [comment]
image
tested on **LOCAL MYSQL DB** it works, encounter issue when connecting with vercel db

**Review by appleaze — APPROVED** [review]
Work Successully on local MySql DB

**Comment by appleaze** [comment]
> image tested on **LOCAL MYSQL DB** it works, encounter issue when connecting with vercel db

image
issue with vercel db

**Comment by IdjiotSandwiches** [comment]
> > image tested on **LOCAL MYSQL DB** it works, encounter issue when connecting with vercel db
> 
> image issue with vercel db

Git pull
Composer install 
Compser dump autoload

**Comment by appleaze** [comment]
image
amaannnnn

**Review by appleaze — APPROVED** [review]

**Pull request merged**
